config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, except: :index do
    resources :doses
  end
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: :true
  validates_presence_of :name
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_presence_of :cocktail, :ingredient, :description
  validates :cocktail, uniqueness: { scope: [:ingredient_id, :cocktail_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates_uniqueness_of :name
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all.sort_by { |cocktail| cocktail.name }
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail.id)
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_dose_form.erb
<%= simple_form_for([@cocktail, @dose], html: {class: "form"}) do |f| %>
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description %>
  </div>
  <%= f.association :ingredient, collection: Ingredient.order('name ASC') %>
  <%= f.submit "Add dose" %>
<% end %>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail, html: {class: "form"}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit <%= @cocktail.name.capitalize %></h1>
<%= render "form", task: @cocktail %>
<%= link_to "Back to cocktails list", root_path, "class" => "menu-action top-right" %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url('<%= cl_image_path "https://res.cloudinary.com/dqckrrqjf/image/upload/v1614364990/cocktail-banner-2_jnbcoe.jpg", width: 1000, height: 400 %>')">
<h1>Cocktails</h1>
<%= link_to "Add a cocktail", new_cocktail_path(@cocktail), "class" => "cocktail-link menu-action top-right" %>

</div>
<div class="index">
<% @cocktails.each do |cocktail| %>
  <%= link_to cocktail_path(cocktail), "class" => "col-lg-3 col-md-4 col-sm-6" do %>
    <div class="card card-content" style="background-image: url('<%= cl_image_path cocktail.photo.key, height: 200, width: 200, crop: :thumb if cocktail.photo.attached? %>')">
    <h3 class="mx-4"><%= cocktail.name.capitalize %></h3>
    </div>
  <% end %>
<% end %>
</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>
<%= render "form", task: @cocktail %>
<%= link_to "Back to list", root_path, "class" => "menu-action top-right" %>

app/views/cocktails/show.html.erb
<div class="cocktail-head">
<h1><%= @cocktail.name.capitalize %></h1>

</div>

<div class="top-right actions">
  <%= link_to edit_cocktail_path, "class" => "edit" do %>
      <i class="far fa-edit"></i>
  <% end %>
  <%= link_to cocktail_path(@cocktail),
            "class" => "delete",
            method: :delete,
            data: { confirm: "Delete #{@cocktail.name}?" } do %>
            <i class="fas fa-trash-alt"></i>
  <% end %>
  <%= link_to root_path, "class" => "menu-action" do %>
  <i class="fas fa-home"></i>
  <% end %>
</div>
<div class="cocktail-details row">
  <div><%= cl_image_tag @cocktail.photo.key, height: 300, width: 300, crop: :fill if @cocktail.photo.attached?%></div>
  <div class="col-sm-12 col-lg-6">
    <h3>Doses</h3>
    <ul class="doses">
    <% @doses.each do |dose| %>
      <li class="dose"><span><%= dose.description %> <%= dose.ingredient.name %></span>
      <%= link_to cocktail_dose_path(@cocktail, dose),
                "class" => "delete",
                method: :delete,
                data: { confirm: "Delete #{dose.description} #{dose.ingredient.name}?" } do %>
                <i class="fas fa-trash-alt"></i>
      <% end %></li>
    <% end %>
    </ul>
  </div>
</div>

<%= render "dose_form", task: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container relative" id="page-content">
    <%= yield %>
  </body>
</html>